namespace ESHIFT
{
    partial class Customer
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle13 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle14 = new System.Windows.Forms.DataGridViewCellStyle();
            this.panelMain = new System.Windows.Forms.Panel();
            this.cmb_SearchBy = new System.Windows.Forms.ComboBox();
            this.dgv_Customers = new System.Windows.Forms.DataGridView();
            this.btn_Search = new System.Windows.Forms.Button();
            this.txt_Search = new System.Windows.Forms.TextBox();
            this.lbl_SearchPrompt = new System.Windows.Forms.Label();
            this.panelDetails = new System.Windows.Forms.Panel();
            this.lbl_JobHistory = new System.Windows.Forms.Label();
            this.dgv_CustomerJobs = new System.Windows.Forms.DataGridView();
            this.grp_Profile = new System.Windows.Forms.GroupBox();
            this.btn_Delete = new System.Windows.Forms.Button();
            this.btn_SaveUpdates = new System.Windows.Forms.Button();
            this.btn_Edit = new System.Windows.Forms.Button();
            this.txt_DetailsAddress = new System.Windows.Forms.TextBox();
            this.lbl_Address = new System.Windows.Forms.Label();
            this.txt_DetailsEmail = new System.Windows.Forms.TextBox();
            this.lbl_Email = new System.Windows.Forms.Label();
            this.txt_DetailsPhone = new System.Windows.Forms.TextBox();
            this.lbl_Phone = new System.Windows.Forms.Label();
            this.txt_DetailsNIC = new System.Windows.Forms.TextBox();
            this.lbl_NIC = new System.Windows.Forms.Label();
            this.txt_DetailsName = new System.Windows.Forms.TextBox();
            this.lbl_Name = new System.Windows.Forms.Label();
            this.btn_Back = new System.Windows.Forms.Button();
            this.lbl_DetailsHeader = new System.Windows.Forms.Label();
            this.panelMain.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_Customers)).BeginInit();
            this.panelDetails.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_CustomerJobs)).BeginInit();
            this.grp_Profile.SuspendLayout();
            this.SuspendLayout();
            this.panelMain.BackColor = System.Drawing.Color.Transparent;
            this.panelMain.Controls.Add(this.cmb_SearchBy);
            this.panelMain.Controls.Add(this.dgv_Customers);
            this.panelMain.Controls.Add(this.btn_Search);
            this.panelMain.Controls.Add(this.txt_Search);
            this.panelMain.Controls.Add(this.lbl_SearchPrompt);
            this.panelMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelMain.Location = new System.Drawing.Point(0, 0);
            this.panelMain.Name = "panelMain";
            this.panelMain.Size = new System.Drawing.Size(1259, 578);
            this.panelMain.TabIndex = 0;
            this.cmb_SearchBy.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmb_SearchBy.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F);
            this.cmb_SearchBy.FormattingEnabled = true;
            this.cmb_SearchBy.Items.AddRange(new object[] {
            "All",
            "Name",
            "NIC",
            "Phone"});
            this.cmb_SearchBy.Location = new System.Drawing.Point(145, 31);
            this.cmb_SearchBy.Name = "cmb_SearchBy";
            this.cmb_SearchBy.Size = new System.Drawing.Size(140, 26);
            this.cmb_SearchBy.TabIndex = 4;
            this.dgv_Customers.AllowUserToAddRows = false;
            this.dgv_Customers.AllowUserToDeleteRows = false;
            this.dgv_Customers.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dgv_Customers.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv_Customers.BackgroundColor = System.Drawing.Color.White;
            dataGridViewCellStyle13.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle13.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle13.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle13.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle13.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle13.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle13.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv_Customers.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle13;
            this.dgv_Customers.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_Customers.EnableHeadersVisualStyles = false;
            this.dgv_Customers.Location = new System.Drawing.Point(23, 76);
            this.dgv_Customers.MultiSelect = false;
            this.dgv_Customers.Name = "dgv_Customers";
            this.dgv_Customers.ReadOnly = true;
            this.dgv_Customers.RowHeadersVisible = false;
            this.dgv_Customers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_Customers.Size = new System.Drawing.Size(1212, 479);
            this.dgv_Customers.TabIndex = 3;
            this.btn_Search.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btn_Search.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Search.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_Search.ForeColor = System.Drawing.Color.White;
            this.btn_Search.Location = new System.Drawing.Point(607, 29);
            this.btn_Search.Name = "btn_Search";
            this.btn_Search.Size = new System.Drawing.Size(107, 30);
            this.btn_Search.TabIndex = 2;
            this.btn_Search.Text = "Search";
            this.btn_Search.UseVisualStyleBackColor = false;
            this.btn_Search.Click += new System.EventHandler(this.btn_Search_Click);
            this.txt_Search.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.txt_Search.Location = new System.Drawing.Point(302, 31);
            this.txt_Search.Name = "txt_Search";
            this.txt_Search.Size = new System.Drawing.Size(294, 26);
            this.txt_Search.TabIndex = 1;
            this.lbl_SearchPrompt.AutoSize = true;
            this.lbl_SearchPrompt.BackColor = System.Drawing.Color.Transparent;
            this.lbl_SearchPrompt.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.lbl_SearchPrompt.Location = new System.Drawing.Point(19, 34);
            this.lbl_SearchPrompt.Name = "lbl_SearchPrompt";
            this.lbl_SearchPrompt.Size = new System.Drawing.Size(89, 19);
            this.lbl_SearchPrompt.TabIndex = 0;
            this.lbl_SearchPrompt.Text = "Search By:";
            this.panelDetails.BackColor = System.Drawing.Color.Transparent;
            this.panelDetails.Controls.Add(this.lbl_JobHistory);
            this.panelDetails.Controls.Add(this.dgv_CustomerJobs);
            this.panelDetails.Controls.Add(this.grp_Profile);
            this.panelDetails.Controls.Add(this.btn_Back);
            this.panelDetails.Controls.Add(this.lbl_DetailsHeader);
            this.panelDetails.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelDetails.Location = new System.Drawing.Point(0, 0);
            this.panelDetails.Name = "panelDetails";
            this.panelDetails.Size = new System.Drawing.Size(1259, 578);
            this.panelDetails.TabIndex = 4;
            this.panelDetails.Visible = false;
            this.lbl_JobHistory.AutoSize = true;
            this.lbl_JobHistory.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.lbl_JobHistory.Location = new System.Drawing.Point(19, 235);
            this.lbl_JobHistory.Name = "lbl_JobHistory";
            this.lbl_JobHistory.Size = new System.Drawing.Size(172, 19);
            this.lbl_JobHistory.TabIndex = 4;
            this.lbl_JobHistory.Text = "Job Requests / History";
            this.dgv_CustomerJobs.AllowUserToAddRows = false;
            this.dgv_CustomerJobs.AllowUserToDeleteRows = false;
            this.dgv_CustomerJobs.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dgv_CustomerJobs.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv_CustomerJobs.BackgroundColor = System.Drawing.Color.White;
            dataGridViewCellStyle14.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle14.BackColor = System.Drawing.Color.DarkSlateGray;
            dataGridViewCellStyle14.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle14.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle14.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle14.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle14.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv_CustomerJobs.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle14;
            this.dgv_CustomerJobs.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_CustomerJobs.EnableHeadersVisualStyles = false;
            this.dgv_CustomerJobs.Location = new System.Drawing.Point(23, 257);
            this.dgv_CustomerJobs.Name = "dgv_CustomerJobs";
            this.dgv_CustomerJobs.ReadOnly = true;
            this.dgv_CustomerJobs.RowHeadersVisible = false;
            this.dgv_CustomerJobs.Size = new System.Drawing.Size(1212, 298);
            this.dgv_CustomerJobs.TabIndex = 3;
            this.grp_Profile.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.grp_Profile.Controls.Add(this.btn_Delete);
            this.grp_Profile.Controls.Add(this.btn_SaveUpdates);
            this.grp_Profile.Controls.Add(this.btn_Edit);
            this.grp_Profile.Controls.Add(this.txt_DetailsAddress);
            this.grp_Profile.Controls.Add(this.lbl_Address);
            this.grp_Profile.Controls.Add(this.txt_DetailsEmail);
            this.grp_Profile.Controls.Add(this.lbl_Email);
            this.grp_Profile.Controls.Add(this.txt_DetailsPhone);
            this.grp_Profile.Controls.Add(this.lbl_Phone);
            this.grp_Profile.Controls.Add(this.txt_DetailsNIC);
            this.grp_Profile.Controls.Add(this.lbl_NIC);
            this.grp_Profile.Controls.Add(this.txt_DetailsName);
            this.grp_Profile.Controls.Add(this.lbl_Name);
            this.grp_Profile.Font = new System.Drawing.Font("Century Gothic", 10F);
            this.grp_Profile.Location = new System.Drawing.Point(23, 56);
            this.grp_Profile.Name = "grp_Profile";
            this.grp_Profile.Size = new System.Drawing.Size(1212, 165);
            this.grp_Profile.TabIndex = 2;
            this.grp_Profile.TabStop = false;
            this.grp_Profile.Text = "Profile Details";
            this.btn_Delete.BackColor = System.Drawing.Color.Red;
            this.btn_Delete.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Delete.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Delete.ForeColor = System.Drawing.Color.White;
            this.btn_Delete.Location = new System.Drawing.Point(603, 104);
            this.btn_Delete.Name = "btn_Delete";
            this.btn_Delete.Size = new System.Drawing.Size(107, 30);
            this.btn_Delete.TabIndex = 12;
            this.btn_Delete.Text = "Delete";
            this.btn_Delete.UseVisualStyleBackColor = false;
            this.btn_Delete.Click += new System.EventHandler(this.btn_Delete_Click);
            this.btn_SaveUpdates.BackColor = System.Drawing.Color.SeaGreen;
            this.btn_SaveUpdates.Enabled = false;
            this.btn_SaveUpdates.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_SaveUpdates.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_SaveUpdates.ForeColor = System.Drawing.Color.White;
            this.btn_SaveUpdates.Location = new System.Drawing.Point(490, 104);
            this.btn_SaveUpdates.Name = "btn_SaveUpdates";
            this.btn_SaveUpdates.Size = new System.Drawing.Size(107, 30);
            this.btn_SaveUpdates.TabIndex = 11;
            this.btn_SaveUpdates.Text = "Save";
            this.btn_SaveUpdates.UseVisualStyleBackColor = false;
            this.btn_SaveUpdates.Click += new System.EventHandler(this.btn_SaveUpdates_Click);
            this.btn_Edit.BackColor = System.Drawing.Color.SteelBlue;
            this.btn_Edit.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Edit.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Edit.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.Location = new System.Drawing.Point(377, 104);
            this.btn_Edit.Name = "btn_Edit";
            this.btn_Edit.Size = new System.Drawing.Size(107, 30);
            this.btn_Edit.TabIndex = 10;
            this.btn_Edit.Text = "Edit";
            this.btn_Edit.UseVisualStyleBackColor = false;
            this.btn_Edit.Click += new System.EventHandler(this.btn_Edit_Click);
            this.txt_DetailsAddress.Location = new System.Drawing.Point(403, 29);
            this.txt_DetailsAddress.Name = "txt_DetailsAddress";
            this.txt_DetailsAddress.ReadOnly = true;
            this.txt_DetailsAddress.Size = new System.Drawing.Size(206, 24);
            this.txt_DetailsAddress.TabIndex = 9;
            this.lbl_Address.AutoSize = true;
            this.lbl_Address.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Address.Location = new System.Drawing.Point(336, 37);
            this.lbl_Address.Name = "lbl_Address";
            this.lbl_Address.Size = new System.Drawing.Size(57, 16);
            this.lbl_Address.TabIndex = 8;
            this.lbl_Address.Text = "Address:";
            this.txt_DetailsEmail.Location = new System.Drawing.Point(82, 134);
            this.txt_DetailsEmail.Name = "txt_DetailsEmail";
            this.txt_DetailsEmail.ReadOnly = true;
            this.txt_DetailsEmail.Size = new System.Drawing.Size(131, 24);
            this.txt_DetailsEmail.TabIndex = 7;
            this.lbl_Email.AutoSize = true;
            this.lbl_Email.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Email.Location = new System.Drawing.Point(20, 134);
            this.lbl_Email.Name = "lbl_Email";
            this.lbl_Email.Size = new System.Drawing.Size(41, 16);
            this.lbl_Email.TabIndex = 6;
            this.lbl_Email.Text = "Email:";
            this.txt_DetailsPhone.Location = new System.Drawing.Point(82, 100);
            this.txt_DetailsPhone.Name = "txt_DetailsPhone";
            this.txt_DetailsPhone.ReadOnly = true;
            this.txt_DetailsPhone.Size = new System.Drawing.Size(131, 24);
            this.txt_DetailsPhone.TabIndex = 5;
            this.lbl_Phone.AutoSize = true;
            this.lbl_Phone.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Phone.Location = new System.Drawing.Point(15, 104);
            this.lbl_Phone.Name = "lbl_Phone";
            this.lbl_Phone.Size = new System.Drawing.Size(47, 16);
            this.lbl_Phone.TabIndex = 4;
            this.lbl_Phone.Text = "Phone:";
            this.txt_DetailsNIC.Location = new System.Drawing.Point(82, 67);
            this.txt_DetailsNIC.Name = "txt_DetailsNIC";
            this.txt_DetailsNIC.ReadOnly = true;
            this.txt_DetailsNIC.Size = new System.Drawing.Size(131, 24);
            this.txt_DetailsNIC.TabIndex = 3;
            this.lbl_NIC.AutoSize = true;
            this.lbl_NIC.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_NIC.Location = new System.Drawing.Point(15, 71);
            this.lbl_NIC.Name = "lbl_NIC";
            this.lbl_NIC.Size = new System.Drawing.Size(32, 16);
            this.lbl_NIC.TabIndex = 2;
            this.lbl_NIC.Text = "NIC:";
            this.txt_DetailsName.Location = new System.Drawing.Point(82, 33);
            this.txt_DetailsName.Name = "txt_DetailsName";
            this.txt_DetailsName.ReadOnly = true;
            this.txt_DetailsName.Size = new System.Drawing.Size(206, 24);
            this.txt_DetailsName.TabIndex = 1;
            this.lbl_Name.AutoSize = true;
            this.lbl_Name.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Name.Location = new System.Drawing.Point(15, 37);
            this.lbl_Name.Name = "lbl_Name";
            this.lbl_Name.Size = new System.Drawing.Size(46, 16);
            this.lbl_Name.TabIndex = 0;
            this.lbl_Name.Text = "Name:";
            this.btn_Back.BackColor = System.Drawing.Color.Gray;
            this.btn_Back.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Back.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_Back.ForeColor = System.Drawing.Color.White;
            this.btn_Back.Location = new System.Drawing.Point(23, 15);
            this.btn_Back.Name = "btn_Back";
            this.btn_Back.Size = new System.Drawing.Size(89, 30);
            this.btn_Back.TabIndex = 1;
            this.btn_Back.Text = "Back";
            this.btn_Back.UseVisualStyleBackColor = false;
            this.btn_Back.Click += new System.EventHandler(this.btn_Back_Click);
            this.lbl_DetailsHeader.AutoSize = true;
            this.lbl_DetailsHeader.Font = new System.Drawing.Font("Century Gothic", 16F, System.Drawing.FontStyle.Bold);
            this.lbl_DetailsHeader.Location = new System.Drawing.Point(127, 16);
            this.lbl_DetailsHeader.Name = "lbl_DetailsHeader";
            this.lbl_DetailsHeader.Size = new System.Drawing.Size(184, 26);
            this.lbl_DetailsHeader.TabIndex = 0;
            this.lbl_DetailsHeader.Text = "Customer Profile";
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.BackgroundImage = global::ESHIFT.Properties.Resources.ChatGPT_Image_Sep_8__2025__12_43_24_AM;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1259, 578);
            this.Controls.Add(this.panelDetails);
            this.Controls.Add(this.panelMain);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Customer";
            this.Text = "Customer";
            this.Load += new System.EventHandler(this.Customer_Load);
            this.panelMain.ResumeLayout(false);
            this.panelMain.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_Customers)).EndInit();
            this.panelDetails.ResumeLayout(false);
            this.panelDetails.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_CustomerJobs)).EndInit();
            this.grp_Profile.ResumeLayout(false);
            this.grp_Profile.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.Panel panelMain;
        private System.Windows.Forms.Panel panelDetails;
        private System.Windows.Forms.DataGridView dgv_Customers;
        private System.Windows.Forms.Button btn_Search;
        private System.Windows.Forms.TextBox txt_Search;
        private System.Windows.Forms.Label lbl_SearchPrompt;
        private System.Windows.Forms.Button btn_Back;
        private System.Windows.Forms.Label lbl_DetailsHeader;
        private System.Windows.Forms.GroupBox grp_Profile;
        private System.Windows.Forms.TextBox txt_DetailsName;
        private System.Windows.Forms.Label lbl_Name;
        private System.Windows.Forms.TextBox txt_DetailsNIC;
        private System.Windows.Forms.Label lbl_NIC;
        private System.Windows.Forms.TextBox txt_DetailsPhone;
        private System.Windows.Forms.Label lbl_Phone;
        private System.Windows.Forms.TextBox txt_DetailsEmail;
        private System.Windows.Forms.Label lbl_Email;
        private System.Windows.Forms.TextBox txt_DetailsAddress;
        private System.Windows.Forms.Label lbl_Address;
        private System.Windows.Forms.Label lbl_JobHistory;
        private System.Windows.Forms.DataGridView dgv_CustomerJobs;
        private System.Windows.Forms.ComboBox cmb_SearchBy;
        private System.Windows.Forms.Button btn_Edit;
        private System.Windows.Forms.Button btn_SaveUpdates;
        private System.Windows.Forms.Button btn_Delete;
    }
}
