namespace ESHIFT
{
    partial class CustomerForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.txt_name = new System.Windows.Forms.TextBox();
            this.txt_NIC = new System.Windows.Forms.TextBox();
            this.txt_Phone = new System.Windows.Forms.TextBox();
            this.txt_Email = new System.Windows.Forms.TextBox();
            this.txt_Address = new System.Windows.Forms.TextBox();
            this.txt_Destination = new System.Windows.Forms.TextBox();
            this.txt_StartLocation = new System.Windows.Forms.TextBox();
            this.txt_item = new System.Windows.Forms.TextBox();
            this.lbl_search = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.lbl_EditNIC = new System.Windows.Forms.Label();
            this.txt_EditNIC = new System.Windows.Forms.TextBox();
            this.btn_delete = new System.Windows.Forms.Button();
            this.btn_Save = new System.Windows.Forms.Button();
            this.btn_UpdateProfile = new System.Windows.Forms.Button();
            this.txt_NewPassword = new System.Windows.Forms.TextBox();
            this.btn_ChangePassword = new System.Windows.Forms.Button();
            this.pnl_Settings = new System.Windows.Forms.Panel();
            this.btn_Back_Settings = new Guna.UI2.WinForms.Guna2Button();
            this.pnl_JobRequest = new System.Windows.Forms.Panel();
            this.DT_PIckup_jobs = new System.Windows.Forms.DateTimePicker();
            this.label_Weight = new System.Windows.Forms.Label();
            this.txt_Weight = new System.Windows.Forms.TextBox();
            this.btn_AddItem = new System.Windows.Forms.Button();
            this.dgv_JobItems = new System.Windows.Forms.DataGridView();
            this.btn_Nav_Settings = new Guna.UI2.WinForms.Guna2Button();
            this.btn_Nav_JobRequest = new Guna.UI2.WinForms.Guna2Button();
            this.btn_Logout = new Guna.UI2.WinForms.Guna2Button();
            this.button1 = new System.Windows.Forms.Button();
            this.btn_RefreshJobs = new System.Windows.Forms.Button();
            this.pnl_MyJobs = new System.Windows.Forms.Panel();
            this.dgv_MyJobs = new System.Windows.Forms.DataGridView();
            this.btn_Nav_MyJobs = new Guna.UI2.WinForms.Guna2Button();
            this.btn_Back_MyJobs = new Guna.UI2.WinForms.Guna2Button();
            this.panelHeader = new System.Windows.Forms.Panel();
            this.labelHeader = new System.Windows.Forms.Label();
            this.pictureBoxLogo = new System.Windows.Forms.PictureBox();
            this.pnl_Settings.SuspendLayout();
            this.pnl_JobRequest.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_JobItems)).BeginInit();
            this.pnl_MyJobs.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_MyJobs)).BeginInit();
            this.panelHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxLogo)).BeginInit();
            this.SuspendLayout();
            this.txt_name.Location = new System.Drawing.Point(360, 22);
            this.txt_name.Name = "txt_name";
            this.txt_name.ReadOnly = true;
            this.txt_name.Size = new System.Drawing.Size(220, 20);
            this.txt_name.TabIndex = 0;
            this.txt_name.TextChanged += new System.EventHandler(this.txt_name_TextChanged);
            this.txt_NIC.Location = new System.Drawing.Point(632, 21);
            this.txt_NIC.Name = "txt_NIC";
            this.txt_NIC.ReadOnly = true;
            this.txt_NIC.Size = new System.Drawing.Size(200, 20);
            this.txt_NIC.TabIndex = 1;
            this.txt_NIC.TextChanged += new System.EventHandler(this.txt_NIC_TextChanged);
            this.txt_Phone.Location = new System.Drawing.Point(150, 20);
            this.txt_Phone.Name = "txt_Phone";
            this.txt_Phone.Size = new System.Drawing.Size(220, 20);
            this.txt_Phone.TabIndex = 2;
            this.txt_Phone.TextChanged += new System.EventHandler(this.txt_Phone_TextChanged);
            this.txt_Email.Location = new System.Drawing.Point(150, 60);
            this.txt_Email.Name = "txt_Email";
            this.txt_Email.Size = new System.Drawing.Size(220, 20);
            this.txt_Email.TabIndex = 3;
            this.txt_Address.Location = new System.Drawing.Point(150, 100);
            this.txt_Address.Name = "txt_Address";
            this.txt_Address.Size = new System.Drawing.Size(220, 20);
            this.txt_Address.TabIndex = 4;
            this.txt_Address.TextChanged += new System.EventHandler(this.txt_Address_TextChanged);
            this.txt_Destination.Location = new System.Drawing.Point(150, 100);
            this.txt_Destination.Name = "txt_Destination";
            this.txt_Destination.Size = new System.Drawing.Size(220, 20);
            this.txt_Destination.TabIndex = 6;
            this.txt_Destination.TextChanged += new System.EventHandler(this.txt_Destination_TextChanged);
            this.txt_StartLocation.Location = new System.Drawing.Point(150, 60);
            this.txt_StartLocation.Name = "txt_StartLocation";
            this.txt_StartLocation.Size = new System.Drawing.Size(220, 20);
            this.txt_StartLocation.TabIndex = 7;
            this.txt_StartLocation.TextChanged += new System.EventHandler(this.txt_StartLocation_TextChanged);
            this.txt_item.Location = new System.Drawing.Point(150, 20);
            this.txt_item.Name = "txt_item";
            this.txt_item.Size = new System.Drawing.Size(220, 20);
            this.txt_item.TabIndex = 8;
            this.txt_item.TextChanged += new System.EventHandler(this.textBox9_TextChanged);
            this.lbl_search.AutoSize = true;
            this.lbl_search.BackColor = System.Drawing.Color.Transparent;
            this.lbl_search.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_search.ForeColor = System.Drawing.Color.White;
            this.lbl_search.Location = new System.Drawing.Point(300, 25);
            this.lbl_search.Name = "lbl_search";
            this.lbl_search.Size = new System.Drawing.Size(42, 16);
            this.lbl_search.TabIndex = 15;
            this.lbl_search.Text = "NAME";
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(20, 20);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(44, 16);
            this.label1.TabIndex = 16;
            this.label1.Text = "Phone";
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(20, 60);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(38, 16);
            this.label2.TabIndex = 17;
            this.label2.Text = "Email";
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(20, 100);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(54, 16);
            this.label3.TabIndex = 18;
            this.label3.Text = "Address";
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(20, 20);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(33, 16);
            this.label4.TabIndex = 19;
            this.label4.Text = "Item";
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(20, 60);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(84, 16);
            this.label5.TabIndex = 20;
            this.label5.Text = "Start Location";
            this.label5.Click += new System.EventHandler(this.label5_Click);
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(20, 100);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(70, 16);
            this.label6.TabIndex = 21;
            this.label6.Text = "Destination";
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(20, 140);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(34, 16);
            this.label7.TabIndex = 22;
            this.label7.Text = "date";
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.Transparent;
            this.label8.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(586, 26);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(29, 16);
            this.label8.TabIndex = 23;
            this.label8.Text = "NIC";
            this.label8.Click += new System.EventHandler(this.label8_Click);
            this.lbl_EditNIC.AutoSize = true;
            this.lbl_EditNIC.BackColor = System.Drawing.Color.Transparent;
            this.lbl_EditNIC.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_EditNIC.Location = new System.Drawing.Point(20, 140);
            this.lbl_EditNIC.Name = "lbl_EditNIC";
            this.lbl_EditNIC.Size = new System.Drawing.Size(29, 16);
            this.lbl_EditNIC.TabIndex = 70;
            this.lbl_EditNIC.Text = "NIC";
            this.txt_EditNIC.Location = new System.Drawing.Point(150, 140);
            this.txt_EditNIC.Name = "txt_EditNIC";
            this.txt_EditNIC.Size = new System.Drawing.Size(220, 20);
            this.txt_EditNIC.TabIndex = 71;
            this.btn_delete.BackColor = System.Drawing.Color.Lime;
            this.btn_delete.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_delete.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_delete.Location = new System.Drawing.Point(340, 400);
            this.btn_delete.Name = "btn_delete";
            this.btn_delete.Size = new System.Drawing.Size(135, 47);
            this.btn_delete.TabIndex = 26;
            this.btn_delete.Text = "Cancel";
            this.btn_delete.UseVisualStyleBackColor = false;
            this.btn_delete.Click += new System.EventHandler(this.btn_delete_Click);
            this.btn_Save.BackColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Save.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_Save.Location = new System.Drawing.Point(150, 400);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.Size = new System.Drawing.Size(141, 47);
            this.btn_Save.TabIndex = 24;
            this.btn_Save.Text = "Request Job";
            this.btn_Save.UseVisualStyleBackColor = false;
            this.btn_Save.Click += new System.EventHandler(this.btn_Save_Click);
            this.btn_UpdateProfile.BackColor = System.Drawing.Color.Lime;
            this.btn_UpdateProfile.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_UpdateProfile.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold);
            this.btn_UpdateProfile.Location = new System.Drawing.Point(150, 180);
            this.btn_UpdateProfile.Name = "btn_UpdateProfile";
            this.btn_UpdateProfile.Size = new System.Drawing.Size(140, 30);
            this.btn_UpdateProfile.TabIndex = 30;
            this.btn_UpdateProfile.Text = "Update Profile";
            this.btn_UpdateProfile.UseVisualStyleBackColor = false;
            this.btn_UpdateProfile.Click += new System.EventHandler(this.btn_UpdateProfile_Click);
            this.txt_NewPassword.Location = new System.Drawing.Point(150, 240);
            this.txt_NewPassword.Name = "txt_NewPassword";
            this.txt_NewPassword.PasswordChar = '*';
            this.txt_NewPassword.Size = new System.Drawing.Size(220, 20);
            this.txt_NewPassword.TabIndex = 31;
            this.btn_ChangePassword.BackColor = System.Drawing.Color.Lime;
            this.btn_ChangePassword.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_ChangePassword.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold);
            this.btn_ChangePassword.Location = new System.Drawing.Point(150, 280);
            this.btn_ChangePassword.Name = "btn_ChangePassword";
            this.btn_ChangePassword.Size = new System.Drawing.Size(140, 30);
            this.btn_ChangePassword.TabIndex = 32;
            this.btn_ChangePassword.Text = "Change Password";
            this.btn_ChangePassword.UseVisualStyleBackColor = false;
            this.btn_ChangePassword.Click += new System.EventHandler(this.btn_ChangePassword_Click);
            this.pnl_Settings.BackColor = System.Drawing.Color.WhiteSmoke;
            this.pnl_Settings.Controls.Add(this.label1);
            this.pnl_Settings.Controls.Add(this.txt_Phone);
            this.pnl_Settings.Controls.Add(this.label2);
            this.pnl_Settings.Controls.Add(this.txt_Email);
            this.pnl_Settings.Controls.Add(this.label3);
            this.pnl_Settings.Controls.Add(this.txt_Address);
            this.pnl_Settings.Controls.Add(this.lbl_EditNIC);
            this.pnl_Settings.Controls.Add(this.txt_EditNIC);
            this.pnl_Settings.Controls.Add(this.btn_UpdateProfile);
            this.pnl_Settings.Controls.Add(this.txt_NewPassword);
            this.pnl_Settings.Controls.Add(this.btn_ChangePassword);
            this.pnl_Settings.Controls.Add(this.btn_delete);
            this.pnl_Settings.Controls.Add(this.btn_Back_Settings);
            this.pnl_Settings.Location = new System.Drawing.Point(50, 160);
            this.pnl_Settings.Name = "pnl_Settings";
            this.pnl_Settings.Size = new System.Drawing.Size(600, 500);
            this.pnl_Settings.TabIndex = 50;
            this.pnl_Settings.Visible = false;
            this.btn_Back_Settings.BorderRadius = 5;
            this.btn_Back_Settings.FillColor = System.Drawing.Color.LightGray;
            this.btn_Back_Settings.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_Back_Settings.ForeColor = System.Drawing.Color.Black;
            this.btn_Back_Settings.Location = new System.Drawing.Point(500, 10);
            this.btn_Back_Settings.Name = "btn_Back_Settings";
            this.btn_Back_Settings.Size = new System.Drawing.Size(80, 25);
            this.btn_Back_Settings.TabIndex = 60;
            this.btn_Back_Settings.Text = "Back";
            this.btn_Back_Settings.Click += new System.EventHandler(this.btn_Back_Settings_Click);
            this.pnl_JobRequest.Controls.Add(this.label4);
            this.pnl_JobRequest.Controls.Add(this.txt_item);
            this.pnl_JobRequest.Controls.Add(this.label5);
            this.pnl_JobRequest.Controls.Add(this.txt_StartLocation);
            this.pnl_JobRequest.Controls.Add(this.label6);
            this.pnl_JobRequest.Controls.Add(this.txt_Destination);
            this.pnl_JobRequest.Controls.Add(this.label7);
            this.pnl_JobRequest.Controls.Add(this.DT_PIckup_jobs);
            this.pnl_JobRequest.Controls.Add(this.label_Weight);
            this.pnl_JobRequest.Controls.Add(this.txt_Weight);
            this.pnl_JobRequest.Controls.Add(this.btn_AddItem);
            this.pnl_JobRequest.Controls.Add(this.dgv_JobItems);
            this.pnl_JobRequest.Controls.Add(this.btn_Save);
            this.pnl_JobRequest.Location = new System.Drawing.Point(50, 160);
            this.pnl_JobRequest.Name = "pnl_JobRequest";
            this.pnl_JobRequest.Size = new System.Drawing.Size(600, 500);
            this.pnl_JobRequest.TabIndex = 51;
            this.pnl_JobRequest.Visible = false;
            this.DT_PIckup_jobs.AccessibleDescription = "DT_Delivery_jobs";
            this.DT_PIckup_jobs.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.DT_PIckup_jobs.Location = new System.Drawing.Point(150, 140);
            this.DT_PIckup_jobs.Name = "DT_PIckup_jobs";
            this.DT_PIckup_jobs.Size = new System.Drawing.Size(221, 20);
            this.DT_PIckup_jobs.TabIndex = 28;
            this.DT_PIckup_jobs.Value = new System.DateTime(2025, 9, 7, 0, 0, 0, 0);
            this.DT_PIckup_jobs.ValueChanged += new System.EventHandler(this.DT_PIckup_jobs_ValueChanged);
            this.label_Weight.AutoSize = true;
            this.label_Weight.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.label_Weight.Location = new System.Drawing.Point(20, 180);
            this.label_Weight.Name = "label_Weight";
            this.label_Weight.Size = new System.Drawing.Size(75, 16);
            this.label_Weight.TabIndex = 29;
            this.label_Weight.Text = "Weight (Kg)";
            this.txt_Weight.Location = new System.Drawing.Point(150, 180);
            this.txt_Weight.Name = "txt_Weight";
            this.txt_Weight.Size = new System.Drawing.Size(220, 20);
            this.txt_Weight.TabIndex = 30;
            this.btn_AddItem.BackColor = System.Drawing.Color.Gold;
            this.btn_AddItem.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_AddItem.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold);
            this.btn_AddItem.Location = new System.Drawing.Point(380, 175);
            this.btn_AddItem.Name = "btn_AddItem";
            this.btn_AddItem.Size = new System.Drawing.Size(100, 30);
            this.btn_AddItem.TabIndex = 60;
            this.btn_AddItem.Text = "Add Item";
            this.btn_AddItem.UseVisualStyleBackColor = false;
            this.btn_AddItem.Click += new System.EventHandler(this.btn_AddItem_Click);
            this.dgv_JobItems.AllowUserToAddRows = false;
            this.dgv_JobItems.AllowUserToDeleteRows = false;
            this.dgv_JobItems.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_JobItems.Location = new System.Drawing.Point(20, 220);
            this.dgv_JobItems.Name = "dgv_JobItems";
            this.dgv_JobItems.ReadOnly = true;
            this.dgv_JobItems.Size = new System.Drawing.Size(500, 150);
            this.dgv_JobItems.TabIndex = 61;
            this.btn_Nav_Settings.FillColor = System.Drawing.Color.Gold;
            this.btn_Nav_Settings.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_Nav_Settings.ForeColor = System.Drawing.Color.White;
            this.btn_Nav_Settings.Location = new System.Drawing.Point(50, 100);
            this.btn_Nav_Settings.Name = "btn_Nav_Settings";
            this.btn_Nav_Settings.Size = new System.Drawing.Size(150, 40);
            this.btn_Nav_Settings.TabIndex = 40;
            this.btn_Nav_Settings.Text = "Edit Settings";
            this.btn_Nav_Settings.Click += new System.EventHandler(this.btn_Nav_Settings_Click);
            this.btn_Nav_JobRequest.FillColor = System.Drawing.Color.DeepSkyBlue;
            this.btn_Nav_JobRequest.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_Nav_JobRequest.ForeColor = System.Drawing.Color.White;
            this.btn_Nav_JobRequest.Location = new System.Drawing.Point(220, 100);
            this.btn_Nav_JobRequest.Name = "btn_Nav_JobRequest";
            this.btn_Nav_JobRequest.Size = new System.Drawing.Size(150, 40);
            this.btn_Nav_JobRequest.TabIndex = 41;
            this.btn_Nav_JobRequest.Text = "Request a Job";
            this.btn_Nav_JobRequest.Click += new System.EventHandler(this.btn_Nav_JobRequest_Click);
            this.btn_Logout.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_Logout.BorderRadius = 15;
            this.btn_Logout.FillColor = System.Drawing.Color.Red;
            this.btn_Logout.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Logout.ForeColor = System.Drawing.Color.White;
            this.btn_Logout.Location = new System.Drawing.Point(1042, 25);
            this.btn_Logout.Name = "btn_Logout";
            this.btn_Logout.Size = new System.Drawing.Size(100, 30);
            this.btn_Logout.TabIndex = 100;
            this.btn_Logout.Text = "Logout";
            this.btn_Logout.Click += new System.EventHandler(this.btn_Logout_Click);
            this.button1.BackColor = System.Drawing.Color.SpringGreen;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.button1.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button1.Location = new System.Drawing.Point(1463, 92);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(89, 30);
            this.button1.TabIndex = 27;
            this.button1.Text = "Exit";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            this.btn_RefreshJobs.Location = new System.Drawing.Point(20, 20);
            this.btn_RefreshJobs.Name = "btn_RefreshJobs";
            this.btn_RefreshJobs.Size = new System.Drawing.Size(100, 30);
            this.btn_RefreshJobs.TabIndex = 1;
            this.btn_RefreshJobs.Text = "Refresh List";
            this.btn_RefreshJobs.UseVisualStyleBackColor = true;
            this.btn_RefreshJobs.Click += new System.EventHandler(this.btn_RefreshJobs_Click);
            this.pnl_MyJobs.Controls.Add(this.btn_RefreshJobs);
            this.pnl_MyJobs.Controls.Add(this.dgv_MyJobs);
            this.pnl_MyJobs.Location = new System.Drawing.Point(50, 160);
            this.pnl_MyJobs.Name = "pnl_MyJobs";
            this.pnl_MyJobs.Size = new System.Drawing.Size(1050, 550);
            this.pnl_MyJobs.TabIndex = 52;
            this.pnl_MyJobs.Visible = false;
            this.dgv_MyJobs.AllowUserToAddRows = false;
            this.dgv_MyJobs.AllowUserToDeleteRows = false;
            this.dgv_MyJobs.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_MyJobs.Location = new System.Drawing.Point(20, 60);
            this.dgv_MyJobs.Name = "dgv_MyJobs";
            this.dgv_MyJobs.ReadOnly = true;
            this.dgv_MyJobs.Size = new System.Drawing.Size(1000, 480);
            this.dgv_MyJobs.TabIndex = 0;
            this.btn_Nav_MyJobs.FillColor = System.Drawing.Color.MediumOrchid;
            this.btn_Nav_MyJobs.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_Nav_MyJobs.ForeColor = System.Drawing.Color.White;
            this.btn_Nav_MyJobs.Location = new System.Drawing.Point(390, 100);
            this.btn_Nav_MyJobs.Name = "btn_Nav_MyJobs";
            this.btn_Nav_MyJobs.Size = new System.Drawing.Size(150, 40);
            this.btn_Nav_MyJobs.TabIndex = 42;
            this.btn_Nav_MyJobs.Text = "My Jobs";
            this.btn_Nav_MyJobs.Click += new System.EventHandler(this.btn_Nav_MyJobs_Click);
            this.btn_Back_MyJobs.BorderRadius = 5;
            this.btn_Back_MyJobs.FillColor = System.Drawing.Color.LightGray;
            this.btn_Back_MyJobs.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_Back_MyJobs.ForeColor = System.Drawing.Color.Black;
            this.btn_Back_MyJobs.Location = new System.Drawing.Point(940, 10);
            this.btn_Back_MyJobs.Name = "btn_Back_MyJobs";
            this.btn_Back_MyJobs.Size = new System.Drawing.Size(80, 25);
            this.btn_Back_MyJobs.TabIndex = 2;
            this.btn_Back_MyJobs.Text = "Back";
            this.btn_Back_MyJobs.Click += new System.EventHandler(this.btn_Back_Settings_Click);
            this.panelHeader.BackColor = System.Drawing.Color.Green;
            this.panelHeader.Controls.Add(this.labelHeader);
            this.panelHeader.Controls.Add(this.pictureBoxLogo);
            this.panelHeader.Controls.Add(this.lbl_search);
            this.panelHeader.Controls.Add(this.txt_name);
            this.panelHeader.Controls.Add(this.label8);
            this.panelHeader.Controls.Add(this.txt_NIC);
            this.panelHeader.Controls.Add(this.btn_Logout);
            this.panelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelHeader.Location = new System.Drawing.Point(0, 0);
            this.panelHeader.Name = "panelHeader";
            this.panelHeader.Size = new System.Drawing.Size(1162, 80);
            this.panelHeader.TabIndex = 22;
            this.labelHeader.AutoSize = true;
            this.labelHeader.Font = new System.Drawing.Font("Cooper Black", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelHeader.ForeColor = System.Drawing.Color.White;
            this.labelHeader.Location = new System.Drawing.Point(150, 25);
            this.labelHeader.Name = "labelHeader";
            this.labelHeader.Size = new System.Drawing.Size(105, 27);
            this.labelHeader.TabIndex = 1;
            this.labelHeader.Text = "ESHIFT";
            this.pictureBoxLogo.Image = global::ESHIFT.Properties.Resources.ChatGPT_Image_Sep_7__2025__02_52_36_PM;
            this.pictureBoxLogo.Location = new System.Drawing.Point(12, 12);
            this.pictureBoxLogo.Name = "pictureBoxLogo";
            this.pictureBoxLogo.Size = new System.Drawing.Size(120, 56);
            this.pictureBoxLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBoxLogo.TabIndex = 0;
            this.pictureBoxLogo.TabStop = false;
            this.BackColor = System.Drawing.Color.LimeGreen;
            this.BackgroundImage = global::ESHIFT.Properties.Resources.ChatGPT_Image_Sep_8__2025__12_43_24_AM;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1162, 643);
            this.Controls.Add(this.panelHeader);
            this.Controls.Add(this.pnl_MyJobs);
            this.Controls.Add(this.pnl_Settings);
            this.Controls.Add(this.pnl_JobRequest);
            this.Controls.Add(this.btn_Nav_Settings);
            this.Controls.Add(this.btn_Nav_JobRequest);
            this.Controls.Add(this.btn_Nav_MyJobs);
            this.Controls.Add(this.button1);
            this.Name = "CustomerForm";
            this.Text = "CustomerForm";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.CustomerForm_Load);
            this.pnl_Settings.ResumeLayout(false);
            this.pnl_Settings.PerformLayout();
            this.pnl_JobRequest.ResumeLayout(false);
            this.pnl_JobRequest.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_JobItems)).EndInit();
            this.pnl_MyJobs.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgv_MyJobs)).EndInit();
            this.panelHeader.ResumeLayout(false);
            this.panelHeader.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxLogo)).EndInit();
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.TextBox txt_name;
        private System.Windows.Forms.TextBox txt_NIC;
        private System.Windows.Forms.TextBox txt_Phone;
        private System.Windows.Forms.TextBox txt_Email;
        private System.Windows.Forms.TextBox txt_Address;
        private System.Windows.Forms.TextBox txt_Destination;
        private System.Windows.Forms.TextBox txt_StartLocation;
        private System.Windows.Forms.TextBox txt_item;
        private System.Windows.Forms.Label lbl_search;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label lbl_EditNIC; // New
        private System.Windows.Forms.TextBox txt_EditNIC; // New
        private System.Windows.Forms.Button btn_delete;
        private System.Windows.Forms.Button btn_Save;
        private System.Windows.Forms.Button btn_UpdateProfile;
        private System.Windows.Forms.TextBox txt_NewPassword;
        private System.Windows.Forms.Button btn_ChangePassword;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.DateTimePicker DT_PIckup_jobs;
        private System.Windows.Forms.TextBox txt_Weight;
        private System.Windows.Forms.Label label_Weight;
        private System.Windows.Forms.DataGridView dgv_MyJobs;
        private System.Windows.Forms.DataGridView dgv_JobItems; // New Grid
        private System.Windows.Forms.Button btn_RefreshJobs;
        private System.Windows.Forms.Button btn_AddItem; // New Button
        private System.Windows.Forms.Panel pnl_Settings;
        private System.Windows.Forms.Panel pnl_JobRequest;
        private System.Windows.Forms.Panel pnl_MyJobs; // New Panel
        private Guna.UI2.WinForms.Guna2Button btn_Nav_Settings;
        private Guna.UI2.WinForms.Guna2Button btn_Nav_JobRequest;
        private Guna.UI2.WinForms.Guna2Button btn_Nav_MyJobs; // New Button
        private Guna.UI2.WinForms.Guna2Button btn_Back_Settings;
        private Guna.UI2.WinForms.Guna2Button btn_Back_MyJobs; // Back for MyJobs
        private Guna.UI2.WinForms.Guna2Button btn_Logout; // Logout Button
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.PictureBox pictureBoxLogo;
        private System.Windows.Forms.Label labelHeader;
    }
}
