namespace ESHIFT
{
    partial class Jobs
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.customerBindingSource1 = new System.Windows.Forms.BindingSource(this.components);
            this.eShiftDBDataSet = new ESHIFT.eShiftDBDataSet();
            this.customerBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.eShiftDBDataSetBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.customerTableAdapter = new ESHIFT.eShiftDBDataSetTableAdapters.CustomerTableAdapter();
            this.pnl_PendingJobs = new System.Windows.Forms.Panel();
            this.dgv_PendingJobs = new System.Windows.Forms.DataGridView();
            this.btn_RefreshPending = new System.Windows.Forms.Button();
            this.pnl_JobManagement = new System.Windows.Forms.Panel();
            this.lbl_SearchPrompt_jobs = new System.Windows.Forms.Label();
            this.cmb_SearchBy_jobs = new System.Windows.Forms.ComboBox();
            this.txt_Search_jobs = new System.Windows.Forms.TextBox();
            this.btn_Search_jobs = new System.Windows.Forms.Button();
            this.dgv_CustomerSearch_jobs = new System.Windows.Forms.DataGridView();
            this.grp_CreateJob = new System.Windows.Forms.GroupBox();
            this.btn_CreateJob = new System.Windows.Forms.Button();
            this.dtp_PickupDate = new System.Windows.Forms.DateTimePicker();
            this.lbl_Date = new System.Windows.Forms.Label();
            this.txt_Weight = new System.Windows.Forms.TextBox();
            this.lbl_Weight = new System.Windows.Forms.Label();
            this.txt_item = new System.Windows.Forms.TextBox();
            this.lbl_Item = new System.Windows.Forms.Label();
            this.txt_Destination = new System.Windows.Forms.TextBox();
            this.lbl_Dest = new System.Windows.Forms.Label();
            this.txt_StartLocation = new System.Windows.Forms.TextBox();
            this.lbl_Start = new System.Windows.Forms.Label();
            this.lbl_SelectedCustomer = new System.Windows.Forms.Label();
            this.btn_Nav_PendingJobs = new System.Windows.Forms.Button();
            this.btn_Nav_ManageJobs = new System.Windows.Forms.Button();
            this.btn_Nav_ProcessingJobs = new System.Windows.Forms.Button();
            this.button1 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.customerBindingSource1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.eShiftDBDataSet)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.customerBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.eShiftDBDataSetBindingSource)).BeginInit();
            this.pnl_PendingJobs.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_PendingJobs)).BeginInit();
            this.pnl_JobManagement.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_CustomerSearch_jobs)).BeginInit();
            this.grp_CreateJob.SuspendLayout();
            this.SuspendLayout();
            this.customerBindingSource1.DataMember = "Customer";
            this.customerBindingSource1.DataSource = this.eShiftDBDataSet;
            this.eShiftDBDataSet.DataSetName = "eShiftDBDataSet";
            this.eShiftDBDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.customerBindingSource.DataMember = "Customer";
            this.customerBindingSource.DataSource = this.eShiftDBDataSetBindingSource;
            this.eShiftDBDataSetBindingSource.DataSource = this.eShiftDBDataSet;
            this.customerTableAdapter.ClearBeforeFill = true;
            this.pnl_PendingJobs.Controls.Add(this.dgv_PendingJobs);
            this.pnl_PendingJobs.Controls.Add(this.btn_RefreshPending);
            this.pnl_PendingJobs.Location = new System.Drawing.Point(33, 52);
            this.pnl_PendingJobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.pnl_PendingJobs.Name = "pnl_PendingJobs";
            this.pnl_PendingJobs.Size = new System.Drawing.Size(733, 260);
            this.pnl_PendingJobs.TabIndex = 110;
            this.dgv_PendingJobs.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_PendingJobs.Location = new System.Drawing.Point(13, 39);
            this.dgv_PendingJobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.dgv_PendingJobs.Name = "dgv_PendingJobs";
            this.dgv_PendingJobs.ReadOnly = true;
            this.dgv_PendingJobs.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_PendingJobs.Size = new System.Drawing.Size(700, 208);
            this.dgv_PendingJobs.TabIndex = 0;
            this.dgv_PendingJobs.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_PendingJobs_CellDoubleClick);
            this.btn_RefreshPending.Location = new System.Drawing.Point(13, 13);
            this.btn_RefreshPending.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_RefreshPending.Name = "btn_RefreshPending";
            this.btn_RefreshPending.Size = new System.Drawing.Size(67, 20);
            this.btn_RefreshPending.TabIndex = 1;
            this.btn_RefreshPending.Text = "Refresh";
            this.btn_RefreshPending.Click += new System.EventHandler(this.btn_RefreshPending_Click);
            this.pnl_JobManagement.Controls.Add(this.lbl_SearchPrompt_jobs);
            this.pnl_JobManagement.Controls.Add(this.cmb_SearchBy_jobs);
            this.pnl_JobManagement.Controls.Add(this.txt_Search_jobs);
            this.pnl_JobManagement.Controls.Add(this.btn_Search_jobs);
            this.pnl_JobManagement.Controls.Add(this.dgv_CustomerSearch_jobs);
            this.pnl_JobManagement.Controls.Add(this.grp_CreateJob);
            this.pnl_JobManagement.Location = new System.Drawing.Point(33, 52);
            this.pnl_JobManagement.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.pnl_JobManagement.Name = "pnl_JobManagement";
            this.pnl_JobManagement.Size = new System.Drawing.Size(746, 355);
            this.pnl_JobManagement.TabIndex = 111;
            this.pnl_JobManagement.Visible = false;
            this.lbl_SearchPrompt_jobs.AutoSize = true;
            this.lbl_SearchPrompt_jobs.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.lbl_SearchPrompt_jobs.Location = new System.Drawing.Point(13, 13);
            this.lbl_SearchPrompt_jobs.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbl_SearchPrompt_jobs.Name = "lbl_SearchPrompt_jobs";
            this.lbl_SearchPrompt_jobs.Size = new System.Drawing.Size(77, 17);
            this.lbl_SearchPrompt_jobs.TabIndex = 0;
            this.lbl_SearchPrompt_jobs.Text = "Search By:";
            this.cmb_SearchBy_jobs.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmb_SearchBy_jobs.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.cmb_SearchBy_jobs.FormattingEnabled = true;
            this.cmb_SearchBy_jobs.Items.AddRange(new object[] {
            "All",
            "Name",
            "Phone",
            "NIC"});
            this.cmb_SearchBy_jobs.Location = new System.Drawing.Point(94, 12);
            this.cmb_SearchBy_jobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.cmb_SearchBy_jobs.Name = "cmb_SearchBy_jobs";
            this.cmb_SearchBy_jobs.Size = new System.Drawing.Size(81, 24);
            this.cmb_SearchBy_jobs.TabIndex = 1;
            this.txt_Search_jobs.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.txt_Search_jobs.Location = new System.Drawing.Point(179, 12);
            this.txt_Search_jobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_Search_jobs.Name = "txt_Search_jobs";
            this.txt_Search_jobs.Size = new System.Drawing.Size(135, 23);
            this.txt_Search_jobs.TabIndex = 2;
            this.btn_Search_jobs.BackColor = System.Drawing.Color.MediumSeaGreen;
            this.btn_Search_jobs.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Search_jobs.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Search_jobs.ForeColor = System.Drawing.Color.White;
            this.btn_Search_jobs.Location = new System.Drawing.Point(318, 12);
            this.btn_Search_jobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_Search_jobs.Name = "btn_Search_jobs";
            this.btn_Search_jobs.Size = new System.Drawing.Size(60, 23);
            this.btn_Search_jobs.TabIndex = 3;
            this.btn_Search_jobs.Text = "Search";
            this.btn_Search_jobs.UseVisualStyleBackColor = false;
            this.btn_Search_jobs.Click += new System.EventHandler(this.btn_Search_jobs_Click);
            this.dgv_CustomerSearch_jobs.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_CustomerSearch_jobs.Location = new System.Drawing.Point(13, 39);
            this.dgv_CustomerSearch_jobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.dgv_CustomerSearch_jobs.Name = "dgv_CustomerSearch_jobs";
            this.dgv_CustomerSearch_jobs.ReadOnly = true;
            this.dgv_CustomerSearch_jobs.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_CustomerSearch_jobs.Size = new System.Drawing.Size(410, 273);
            this.dgv_CustomerSearch_jobs.TabIndex = 4;
            this.dgv_CustomerSearch_jobs.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_CustomerSearch_jobs_CellDoubleClick);
            this.grp_CreateJob.Controls.Add(this.btn_CreateJob);
            this.grp_CreateJob.Controls.Add(this.dtp_PickupDate);
            this.grp_CreateJob.Controls.Add(this.lbl_Date);
            this.grp_CreateJob.Controls.Add(this.txt_Weight);
            this.grp_CreateJob.Controls.Add(this.lbl_Weight);
            this.grp_CreateJob.Controls.Add(this.txt_item);
            this.grp_CreateJob.Controls.Add(this.lbl_Item);
            this.grp_CreateJob.Controls.Add(this.txt_Destination);
            this.grp_CreateJob.Controls.Add(this.lbl_Dest);
            this.grp_CreateJob.Controls.Add(this.txt_StartLocation);
            this.grp_CreateJob.Controls.Add(this.lbl_Start);
            this.grp_CreateJob.Controls.Add(this.lbl_SelectedCustomer);
            this.grp_CreateJob.Font = new System.Drawing.Font("Century Gothic", 10F);
            this.grp_CreateJob.Location = new System.Drawing.Point(427, 39);
            this.grp_CreateJob.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.grp_CreateJob.Name = "grp_CreateJob";
            this.grp_CreateJob.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.grp_CreateJob.Size = new System.Drawing.Size(293, 273);
            this.grp_CreateJob.TabIndex = 5;
            this.grp_CreateJob.TabStop = false;
            this.grp_CreateJob.Text = "Create Job";
            this.btn_CreateJob.BackColor = System.Drawing.Color.DodgerBlue;
            this.btn_CreateJob.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_CreateJob.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_CreateJob.ForeColor = System.Drawing.Color.White;
            this.btn_CreateJob.Location = new System.Drawing.Point(14, 251);
            this.btn_CreateJob.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_CreateJob.Name = "btn_CreateJob";
            this.btn_CreateJob.Size = new System.Drawing.Size(267, 26);
            this.btn_CreateJob.TabIndex = 11;
            this.btn_CreateJob.Text = "Create Job Request";
            this.btn_CreateJob.UseVisualStyleBackColor = false;
            this.btn_CreateJob.Click += new System.EventHandler(this.btn_CreateJob_Click);
            this.dtp_PickupDate.Location = new System.Drawing.Point(13, 223);
            this.dtp_PickupDate.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.dtp_PickupDate.Name = "dtp_PickupDate";
            this.dtp_PickupDate.Size = new System.Drawing.Size(268, 24);
            this.dtp_PickupDate.TabIndex = 10;
            this.lbl_Date.AutoSize = true;
            this.lbl_Date.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Date.Location = new System.Drawing.Point(13, 205);
            this.lbl_Date.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbl_Date.Name = "lbl_Date";
            this.lbl_Date.Size = new System.Drawing.Size(77, 16);
            this.lbl_Date.TabIndex = 9;
            this.lbl_Date.Text = "Pickup Date";
            this.txt_Weight.Location = new System.Drawing.Point(14, 184);
            this.txt_Weight.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_Weight.Name = "txt_Weight";
            this.txt_Weight.Size = new System.Drawing.Size(268, 24);
            this.txt_Weight.TabIndex = 8;
            this.lbl_Weight.AutoSize = true;
            this.lbl_Weight.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Weight.Location = new System.Drawing.Point(13, 172);
            this.lbl_Weight.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbl_Weight.Name = "lbl_Weight";
            this.lbl_Weight.Size = new System.Drawing.Size(75, 16);
            this.lbl_Weight.TabIndex = 7;
            this.lbl_Weight.Text = "Weight (Kg)";
            this.txt_item.Location = new System.Drawing.Point(14, 146);
            this.txt_item.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_item.Name = "txt_item";
            this.txt_item.Size = new System.Drawing.Size(268, 24);
            this.txt_item.TabIndex = 6;
            this.lbl_Item.AutoSize = true;
            this.lbl_Item.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Item.Location = new System.Drawing.Point(13, 128);
            this.lbl_Item.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbl_Item.Name = "lbl_Item";
            this.lbl_Item.Size = new System.Drawing.Size(101, 16);
            this.lbl_Item.TabIndex = 5;
            this.lbl_Item.Text = "Item Description";
            this.txt_Destination.Location = new System.Drawing.Point(13, 102);
            this.txt_Destination.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_Destination.Name = "txt_Destination";
            this.txt_Destination.Size = new System.Drawing.Size(268, 24);
            this.txt_Destination.TabIndex = 4;
            this.lbl_Dest.AutoSize = true;
            this.lbl_Dest.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Dest.Location = new System.Drawing.Point(13, 84);
            this.lbl_Dest.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbl_Dest.Name = "lbl_Dest";
            this.lbl_Dest.Size = new System.Drawing.Size(70, 16);
            this.lbl_Dest.TabIndex = 3;
            this.lbl_Dest.Text = "Destination";
            this.txt_StartLocation.Location = new System.Drawing.Point(13, 58);
            this.txt_StartLocation.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_StartLocation.Name = "txt_StartLocation";
            this.txt_StartLocation.Size = new System.Drawing.Size(268, 24);
            this.txt_StartLocation.TabIndex = 2;
            this.lbl_Start.AutoSize = true;
            this.lbl_Start.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Start.Location = new System.Drawing.Point(13, 40);
            this.lbl_Start.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbl_Start.Name = "lbl_Start";
            this.lbl_Start.Size = new System.Drawing.Size(84, 16);
            this.lbl_Start.TabIndex = 1;
            this.lbl_Start.Text = "Start Location";
            this.lbl_SelectedCustomer.AutoSize = true;
            this.lbl_SelectedCustomer.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_SelectedCustomer.ForeColor = System.Drawing.Color.RoyalBlue;
            this.lbl_SelectedCustomer.Location = new System.Drawing.Point(13, 23);
            this.lbl_SelectedCustomer.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbl_SelectedCustomer.Name = "lbl_SelectedCustomer";
            this.lbl_SelectedCustomer.Size = new System.Drawing.Size(178, 16);
            this.lbl_SelectedCustomer.TabIndex = 0;
            this.lbl_SelectedCustomer.Text = "Select a customer from the list";
            this.lbl_SelectedCustomer.Click += new System.EventHandler(this.lbl_SelectedCustomer_Click);
            this.btn_Nav_PendingJobs.BackColor = System.Drawing.Color.Orange;
            this.btn_Nav_PendingJobs.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Nav_PendingJobs.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Nav_PendingJobs.Location = new System.Drawing.Point(33, 13);
            this.btn_Nav_PendingJobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_Nav_PendingJobs.Name = "btn_Nav_PendingJobs";
            this.btn_Nav_PendingJobs.Size = new System.Drawing.Size(100, 26);
            this.btn_Nav_PendingJobs.TabIndex = 101;
            this.btn_Nav_PendingJobs.Text = "New Jobs";
            this.btn_Nav_PendingJobs.UseVisualStyleBackColor = false;
            this.btn_Nav_PendingJobs.Click += new System.EventHandler(this.btn_Nav_PendingJobs_Click);
            this.btn_Nav_ManageJobs.BackColor = System.Drawing.Color.CornflowerBlue;
            this.btn_Nav_ManageJobs.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Nav_ManageJobs.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Nav_ManageJobs.Location = new System.Drawing.Point(147, 13);
            this.btn_Nav_ManageJobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_Nav_ManageJobs.Name = "btn_Nav_ManageJobs";
            this.btn_Nav_ManageJobs.Size = new System.Drawing.Size(100, 26);
            this.btn_Nav_ManageJobs.TabIndex = 102;
            this.btn_Nav_ManageJobs.Text = "Create Job";
            this.btn_Nav_ManageJobs.UseVisualStyleBackColor = false;
            this.btn_Nav_ManageJobs.Click += new System.EventHandler(this.btn_Nav_ManageJobs_Click);
            this.btn_Nav_ProcessingJobs.BackColor = System.Drawing.Color.MediumPurple;
            this.btn_Nav_ProcessingJobs.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Nav_ProcessingJobs.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Nav_ProcessingJobs.Location = new System.Drawing.Point(260, 13);
            this.btn_Nav_ProcessingJobs.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_Nav_ProcessingJobs.Name = "btn_Nav_ProcessingJobs";
            this.btn_Nav_ProcessingJobs.Size = new System.Drawing.Size(100, 26);
            this.btn_Nav_ProcessingJobs.TabIndex = 103;
            this.btn_Nav_ProcessingJobs.Text = "Processing Jobs";
            this.btn_Nav_ProcessingJobs.UseVisualStyleBackColor = false;
            this.btn_Nav_ProcessingJobs.Click += new System.EventHandler(this.btn_Nav_ProcessingJobs_Click);
            this.button1.Location = new System.Drawing.Point(0, 0);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 23);
            this.button1.TabIndex = 0;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::ESHIFT.Properties.Resources.ChatGPT_Image_Sep_8__2025__12_43_24_AM;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(834, 418);
            this.Controls.Add(this.btn_Nav_ManageJobs);
            this.Controls.Add(this.btn_Nav_ProcessingJobs);
            this.Controls.Add(this.btn_Nav_PendingJobs);
            this.Controls.Add(this.pnl_JobManagement);
            this.Controls.Add(this.pnl_PendingJobs);
            this.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.Name = "Jobs";
            ((System.ComponentModel.ISupportInitialize)(this.customerBindingSource1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.eShiftDBDataSet)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.customerBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.eShiftDBDataSetBindingSource)).EndInit();
            this.pnl_PendingJobs.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgv_PendingJobs)).EndInit();
            this.pnl_JobManagement.ResumeLayout(false);
            this.pnl_JobManagement.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_CustomerSearch_jobs)).EndInit();
            this.grp_CreateJob.ResumeLayout(false);
            this.grp_CreateJob.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.BindingSource eShiftDBDataSetBindingSource;
        private eShiftDBDataSet eShiftDBDataSet;
        private System.Windows.Forms.BindingSource customerBindingSource;
        private eShiftDBDataSetTableAdapters.CustomerTableAdapter customerTableAdapter;
        private System.Windows.Forms.BindingSource customerBindingSource1;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Panel pnl_PendingJobs;
        private System.Windows.Forms.DataGridView dgv_PendingJobs;
        private System.Windows.Forms.Button btn_RefreshPending;
        private System.Windows.Forms.Label lbl_SearchPrompt_jobs;
        private System.Windows.Forms.ComboBox cmb_SearchBy_jobs;
        private System.Windows.Forms.Panel pnl_JobManagement;
        private System.Windows.Forms.TextBox txt_Search_jobs;
        private System.Windows.Forms.Button btn_Search_jobs;
        private System.Windows.Forms.DataGridView dgv_CustomerSearch_jobs;
        private System.Windows.Forms.GroupBox grp_CreateJob;
        private System.Windows.Forms.Label lbl_SelectedCustomer;
        private System.Windows.Forms.TextBox txt_StartLocation;
        private System.Windows.Forms.Label lbl_Start;
        private System.Windows.Forms.TextBox txt_Destination;
        private System.Windows.Forms.Label lbl_Dest;
        private System.Windows.Forms.Label lbl_Date;
        private System.Windows.Forms.DateTimePicker dtp_PickupDate;
        private System.Windows.Forms.Button btn_CreateJob;
        private System.Windows.Forms.Button btn_Nav_PendingJobs;
        private System.Windows.Forms.Button btn_Nav_ManageJobs;
        private System.Windows.Forms.Button btn_Nav_ProcessingJobs;
        private System.Windows.Forms.Label lbl_Item;
        private System.Windows.Forms.TextBox txt_item;
        private System.Windows.Forms.Label lbl_Weight;
        private System.Windows.Forms.TextBox txt_Weight;
    }
}
