namespace ESHIFT
{
    partial class TransportUnit
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.lbl_Title = new System.Windows.Forms.Label();
            this.txt_VehicleType = new System.Windows.Forms.TextBox();
            this.lbl_VehicleType = new System.Windows.Forms.Label();
            this.grp_Search = new System.Windows.Forms.GroupBox();
            this.btn_ViewAll = new System.Windows.Forms.Button();
            this.btn_Search = new System.Windows.Forms.Button();
            this.txt_Search = new System.Windows.Forms.TextBox();
            this.cmb_SearchBy = new System.Windows.Forms.ComboBox();
            this.lbl_SearchBy = new System.Windows.Forms.Label();
            this.grp_Vehicle = new System.Windows.Forms.GroupBox();
            this.cmb_Status = new System.Windows.Forms.ComboBox();
            this.lbl_Status = new System.Windows.Forms.Label();
            this.txt_ContainerID = new System.Windows.Forms.TextBox();
            this.lbl_ContainerID = new System.Windows.Forms.Label();
            this.txt_NumberPlate = new System.Windows.Forms.TextBox();
            this.lbl_NumberPlate = new System.Windows.Forms.Label();
            this.txt_UnitID = new System.Windows.Forms.TextBox();
            this.lbl_UnitID = new System.Windows.Forms.Label();
            this.grp_Driver = new System.Windows.Forms.GroupBox();
            this.txt_DriverNIC = new System.Windows.Forms.TextBox();
            this.lbl_DriverNIC = new System.Windows.Forms.Label();
            this.txt_DriverPhone = new System.Windows.Forms.TextBox();
            this.lbl_DriverPhone = new System.Windows.Forms.Label();
            this.txt_DriverName = new System.Windows.Forms.TextBox();
            this.lbl_DriverName = new System.Windows.Forms.Label();
            this.grp_Assistant = new System.Windows.Forms.GroupBox();
            this.txt_AssistantNIC = new System.Windows.Forms.TextBox();
            this.lbl_AssistantNIC = new System.Windows.Forms.Label();
            this.txt_AssistantPhone = new System.Windows.Forms.TextBox();
            this.lbl_AssistantPhone = new System.Windows.Forms.Label();
            this.txt_AssistantName = new System.Windows.Forms.TextBox();
            this.lbl_AssistantName = new System.Windows.Forms.Label();
            this.btn_Register = new System.Windows.Forms.Button();
            this.btn_New = new System.Windows.Forms.Button();
            this.btn_Update = new System.Windows.Forms.Button();
            this.btn_Delete = new System.Windows.Forms.Button();
            this.btn_Clear = new System.Windows.Forms.Button();
            this.btn_Clear = new System.Windows.Forms.Button();
            this.btn_Cancel = new System.Windows.Forms.Button(); 
            this.btn_ShowJob = new System.Windows.Forms.Button(); // Instantiation
            this.dgv_TransportList = new System.Windows.Forms.DataGridView();
            this.grp_Search.SuspendLayout();
            this.grp_Vehicle.SuspendLayout();
            this.grp_Driver.SuspendLayout();
            this.grp_Assistant.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_TransportList)).BeginInit();
            this.SuspendLayout();
            this.lbl_Title.AutoSize = true;
            this.lbl_Title.Font = new System.Drawing.Font("Century Gothic", 16F, System.Drawing.FontStyle.Bold);
            this.lbl_Title.Location = new System.Drawing.Point(450, 20);
            this.lbl_Title.Name = "lbl_Title";
            this.lbl_Title.Size = new System.Drawing.Size(434, 38);
            this.lbl_Title.Text = "Transport Unit Management";
            this.grp_Search.Controls.Add(this.btn_ViewAll);
            this.grp_Search.Controls.Add(this.btn_Search);
            this.grp_Search.Controls.Add(this.txt_Search);
            this.grp_Search.Controls.Add(this.cmb_SearchBy);
            this.grp_Search.Controls.Add(this.lbl_SearchBy);
            this.grp_Search.Font = new System.Drawing.Font("Century Gothic", 9F);
            this.grp_Search.Location = new System.Drawing.Point(20, 70);
            this.grp_Search.Name = "grp_Search";
            this.grp_Search.Size = new System.Drawing.Size(1200, 80);
            this.grp_Search.TabIndex = 0;
            this.grp_Search.TabStop = false;
            this.grp_Search.Text = "Search";
            this.cmb_SearchBy.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmb_SearchBy.FormattingEnabled = true;
            this.cmb_SearchBy.Items.AddRange(new object[] { "Unit ID", "Number Plate", "Driver Name", "Assistant Name" });
            this.cmb_SearchBy.Location = new System.Drawing.Point(120, 30);
            this.cmb_SearchBy.Name = "cmb_SearchBy";
            this.cmb_SearchBy.Size = new System.Drawing.Size(150, 29);
            this.lbl_SearchBy.AutoSize = true;
            this.lbl_SearchBy.Location = new System.Drawing.Point(20, 33);
            this.lbl_SearchBy.Name = "lbl_SearchBy";
            this.lbl_SearchBy.Text = "Search By:";
            this.txt_Search.Location = new System.Drawing.Point(300, 30);
            this.txt_Search.Name = "txt_Search";
            this.txt_Search.Size = new System.Drawing.Size(400, 30);
            this.btn_Search.BackColor = System.Drawing.Color.SpringGreen;
            this.btn_Search.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Search.Location = new System.Drawing.Point(720, 28);
            this.btn_Search.Name = "btn_Search";
            this.btn_Search.Size = new System.Drawing.Size(100, 32);
            this.btn_Search.Text = "Search";
            this.btn_Search.UseVisualStyleBackColor = false;
            this.btn_Search.Click += new System.EventHandler(this.btn_Search_Click);
            this.btn_ViewAll.BackColor = System.Drawing.Color.PaleTurquoise;
            this.btn_ViewAll.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_ViewAll.Location = new System.Drawing.Point(840, 28);
            this.btn_ViewAll.Name = "btn_ViewAll";
            this.btn_ViewAll.Size = new System.Drawing.Size(100, 32);
            this.btn_ViewAll.Text = "View All";
            this.btn_ViewAll.UseVisualStyleBackColor = false;
            this.btn_ViewAll.Click += new System.EventHandler(this.btn_ViewAll_Click);
            this.grp_Vehicle.Controls.Add(this.txt_VehicleType);
            this.grp_Vehicle.Controls.Add(this.lbl_VehicleType);
            this.grp_Vehicle.Controls.Add(this.cmb_Status);
            this.grp_Vehicle.Controls.Add(this.lbl_Status);
            this.grp_Vehicle.Controls.Add(this.txt_ContainerID);
            this.grp_Vehicle.Controls.Add(this.lbl_ContainerID);
            this.grp_Vehicle.Controls.Add(this.txt_NumberPlate);
            this.grp_Vehicle.Controls.Add(this.lbl_NumberPlate);
            this.grp_Vehicle.Controls.Add(this.txt_UnitID);
            this.grp_Vehicle.Controls.Add(this.lbl_UnitID);
            this.grp_Vehicle.Font = new System.Drawing.Font("Century Gothic", 9F);
            this.grp_Vehicle.Location = new System.Drawing.Point(20, 160);
            this.grp_Vehicle.Name = "grp_Vehicle";
            this.grp_Vehicle.Size = new System.Drawing.Size(380, 290);
            this.grp_Vehicle.Controls.Add(this.btn_ShowJob);
            this.grp_Vehicle.TabStop = false;
            this.grp_Vehicle.Text = "Vehicle Details";
            this.cmb_Status.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmb_Status.FormattingEnabled = true;
            this.cmb_Status.Items.AddRange(new object[] { "Available", "Booked", "Maintenance" });
            this.cmb_Status.Location = new System.Drawing.Point(140, 187);
            this.cmb_Status.Name = "cmb_Status";
            this.cmb_Status.Size = new System.Drawing.Size(200, 29);
            this.btn_ShowJob.BackColor = System.Drawing.Color.LightSkyBlue;
            this.btn_ShowJob.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_ShowJob.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold);
            this.btn_ShowJob.Location = new System.Drawing.Point(345, 187); 
            this.btn_ShowJob.Name = "btn_ShowJob";
            this.btn_ShowJob.Size = new System.Drawing.Size(25, 29);
            this.btn_ShowJob.Text = "?";
            this.btn_ShowJob.UseVisualStyleBackColor = false;
            this.btn_ShowJob.Click += new System.EventHandler(this.btn_ShowJob_Click);
            this.lbl_Status.AutoSize = true;
            this.lbl_Status.Location = new System.Drawing.Point(20, 190);
            this.lbl_Status.Name = "lbl_Status";
            this.lbl_Status.Text = "Status:";
            this.txt_VehicleType.Location = new System.Drawing.Point(140, 237);
            this.txt_VehicleType.Name = "txt_VehicleType";
            this.txt_VehicleType.Size = new System.Drawing.Size(200, 30);
            this.lbl_VehicleType.AutoSize = true;
            this.lbl_VehicleType.Location = new System.Drawing.Point(20, 240);
            this.lbl_VehicleType.Name = "lbl_VehicleType";
            this.lbl_VehicleType.Text = "Vehicle Type:";
            this.lbl_UnitID.AutoSize = true;
            this.lbl_UnitID.Location = new System.Drawing.Point(20, 40);
            this.lbl_UnitID.Name = "lbl_UnitID";
            this.lbl_UnitID.Text = "Unit ID:";
            this.txt_UnitID.Location = new System.Drawing.Point(140, 37);
            this.txt_UnitID.Name = "txt_UnitID";
            this.txt_UnitID.ReadOnly = true;
            this.txt_UnitID.Size = new System.Drawing.Size(200, 30);
            this.lbl_NumberPlate.AutoSize = true;
            this.lbl_NumberPlate.Location = new System.Drawing.Point(20, 90);
            this.lbl_NumberPlate.Name = "lbl_NumberPlate";
            this.lbl_NumberPlate.Text = "No Plate:";
            this.txt_NumberPlate.Location = new System.Drawing.Point(140, 87);
            this.txt_NumberPlate.Name = "txt_NumberPlate";
            this.txt_NumberPlate.Size = new System.Drawing.Size(200, 30);
            this.lbl_ContainerID.AutoSize = true;
            this.lbl_ContainerID.Location = new System.Drawing.Point(20, 140);
            this.lbl_ContainerID.Name = "lbl_ContainerID";
            this.lbl_ContainerID.Text = "Container ID:";
            this.txt_ContainerID.Location = new System.Drawing.Point(140, 137);
            this.txt_ContainerID.Name = "txt_ContainerID";
            this.txt_ContainerID.Size = new System.Drawing.Size(200, 30);
            this.grp_Driver.Controls.Add(this.txt_DriverNIC);
            this.grp_Driver.Controls.Add(this.lbl_DriverNIC);
            this.grp_Driver.Controls.Add(this.txt_DriverPhone);
            this.grp_Driver.Controls.Add(this.lbl_DriverPhone);
            this.grp_Driver.Controls.Add(this.txt_DriverName);
            this.grp_Driver.Controls.Add(this.lbl_DriverName);
            this.grp_Driver.Font = new System.Drawing.Font("Century Gothic", 9F);
            this.grp_Driver.Location = new System.Drawing.Point(430, 160);
            this.grp_Driver.Name = "grp_Driver";
            this.grp_Driver.Size = new System.Drawing.Size(380, 240);
            this.grp_Driver.TabStop = false;
            this.grp_Driver.Text = "Driver Details";
            this.lbl_DriverName.AutoSize = true;
            this.lbl_DriverName.Location = new System.Drawing.Point(20, 40);
            this.lbl_DriverName.Name = "lbl_DriverName";
            this.lbl_DriverName.Text = "Name:";
            this.txt_DriverName.Location = new System.Drawing.Point(140, 37);
            this.txt_DriverName.Name = "txt_DriverName";
            this.txt_DriverName.Size = new System.Drawing.Size(200, 30);
            this.lbl_DriverPhone.AutoSize = true;
            this.lbl_DriverPhone.Location = new System.Drawing.Point(20, 90);
            this.lbl_DriverPhone.Name = "lbl_DriverPhone";
            this.lbl_DriverPhone.Text = "Phone:";
            this.txt_DriverPhone.Location = new System.Drawing.Point(140, 87);
            this.txt_DriverPhone.Name = "txt_DriverPhone";
            this.txt_DriverPhone.Size = new System.Drawing.Size(200, 30);
            this.lbl_DriverNIC.AutoSize = true;
            this.lbl_DriverNIC.Location = new System.Drawing.Point(20, 140);
            this.lbl_DriverNIC.Name = "lbl_DriverNIC";
            this.lbl_DriverNIC.Text = "NIC:";
            this.txt_DriverNIC.Location = new System.Drawing.Point(140, 137);
            this.txt_DriverNIC.Name = "txt_DriverNIC";
            this.txt_DriverNIC.Size = new System.Drawing.Size(200, 30);
            this.grp_Assistant.Controls.Add(this.txt_AssistantNIC);
            this.grp_Assistant.Controls.Add(this.lbl_AssistantNIC);
            this.grp_Assistant.Controls.Add(this.txt_AssistantPhone);
            this.grp_Assistant.Controls.Add(this.lbl_AssistantPhone);
            this.grp_Assistant.Controls.Add(this.txt_AssistantName);
            this.grp_Assistant.Controls.Add(this.lbl_AssistantName);
            this.grp_Assistant.Font = new System.Drawing.Font("Century Gothic", 9F);
            this.grp_Assistant.Location = new System.Drawing.Point(840, 160);
            this.grp_Assistant.Name = "grp_Assistant";
            this.grp_Assistant.Size = new System.Drawing.Size(380, 240);
            this.grp_Assistant.TabStop = false;
            this.grp_Assistant.Text = "Assistant Details";
            this.lbl_AssistantName.AutoSize = true;
            this.lbl_AssistantName.Location = new System.Drawing.Point(20, 40);
            this.lbl_AssistantName.Name = "lbl_AssistantName";
            this.lbl_AssistantName.Text = "Name:";
            this.txt_AssistantName.Location = new System.Drawing.Point(140, 37);
            this.txt_AssistantName.Name = "txt_AssistantName";
            this.txt_AssistantName.Size = new System.Drawing.Size(200, 30);
            this.lbl_AssistantPhone.AutoSize = true;
            this.lbl_AssistantPhone.Location = new System.Drawing.Point(20, 90);
            this.lbl_AssistantPhone.Name = "lbl_AssistantPhone";
            this.lbl_AssistantPhone.Text = "Phone:";
            this.txt_AssistantPhone.Location = new System.Drawing.Point(140, 87);
            this.txt_AssistantPhone.Name = "txt_AssistantPhone";
            this.txt_AssistantPhone.Size = new System.Drawing.Size(200, 30);
            this.lbl_AssistantNIC.AutoSize = true;
            this.lbl_AssistantNIC.Location = new System.Drawing.Point(20, 140);
            this.lbl_AssistantNIC.Name = "lbl_AssistantNIC";
            this.lbl_AssistantNIC.Text = "NIC:";
            this.txt_AssistantNIC.Location = new System.Drawing.Point(140, 137);
            this.txt_AssistantNIC.Name = "txt_AssistantNIC";
            this.txt_AssistantNIC.Size = new System.Drawing.Size(200, 30);
            this.btn_New.BackColor = System.Drawing.Color.DeepSkyBlue;
            this.btn_New.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_New.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_New.Location = new System.Drawing.Point(20, 180); 
            this.btn_New.Name = "btn_New";
            this.btn_New.Size = new System.Drawing.Size(200, 40);
            this.btn_New.Text = "+ New Unit";
            this.btn_New.UseVisualStyleBackColor = false;
            this.btn_New.Click += new System.EventHandler(this.btn_New_Click);
            this.btn_Register.BackColor = System.Drawing.Color.SpringGreen;
            this.btn_Register.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Register.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Register.Location = new System.Drawing.Point(430, 470);
            this.btn_Register.Name = "btn_Register";
            this.btn_Register.Size = new System.Drawing.Size(100, 40);
            this.btn_Register.Text = "Register";
            this.btn_Register.UseVisualStyleBackColor = false;
            this.btn_Register.Click += new System.EventHandler(this.btn_Register_Click);
            this.btn_Update.BackColor = System.Drawing.Color.Khaki;
            this.btn_Update.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Update.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Update.Location = new System.Drawing.Point(550, 470);
            this.btn_Update.Name = "btn_Update";
            this.btn_Update.Size = new System.Drawing.Size(100, 40);
            this.btn_Update.Text = "Update";
            this.btn_Update.UseVisualStyleBackColor = false;
            this.btn_Update.Click += new System.EventHandler(this.btn_Update_Click);
            this.btn_Delete.BackColor = System.Drawing.Color.LightCoral;
            this.btn_Delete.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Delete.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Delete.Location = new System.Drawing.Point(670, 470);
            this.btn_Delete.Name = "btn_Delete";
            this.btn_Delete.Size = new System.Drawing.Size(100, 40);
            this.btn_Delete.Text = "Delete";
            this.btn_Delete.UseVisualStyleBackColor = false;
            this.btn_Delete.Click += new System.EventHandler(this.btn_Delete_Click);
            this.btn_Clear.BackColor = System.Drawing.Color.LightGray;
            this.btn_Clear.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Clear.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Clear.Location = new System.Drawing.Point(790, 470);
            this.btn_Clear.Name = "btn_Clear";
            this.btn_Clear.Size = new System.Drawing.Size(100, 40);
            this.btn_Clear.Text = "Clear";
            this.btn_Clear.UseVisualStyleBackColor = false;
            this.btn_Clear.Click += new System.EventHandler(this.btn_Clear_Click);
            this.btn_Cancel.BackColor = System.Drawing.Color.Tomato;
            this.btn_Cancel.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btn_Cancel.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Cancel.ForeColor = System.Drawing.Color.White;
            this.btn_Cancel.Location = new System.Drawing.Point(910, 470);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.Size = new System.Drawing.Size(100, 40);
            this.btn_Cancel.Text = "Cancel";
            this.btn_Cancel.UseVisualStyleBackColor = false;
            this.btn_Cancel.Click += new System.EventHandler(this.btn_Cancel_Click);
            this.dgv_TransportList.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_TransportList.Location = new System.Drawing.Point(20, 240);
            this.dgv_TransportList.Name = "dgv_TransportList";
            this.dgv_TransportList.ReadOnly = true;
            this.dgv_TransportList.RowHeadersWidth = 51;
            this.dgv_TransportList.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_TransportList.Size = new System.Drawing.Size(1200, 440);
            this.dgv_TransportList.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_TransportList_CellClick);
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1250, 700);
            this.Controls.Add(this.lbl_Title);
            this.Controls.Add(this.grp_Search);
            this.Controls.Add(this.grp_Vehicle);
            this.Controls.Add(this.grp_Driver);
            this.Controls.Add(this.grp_Assistant);
            this.Controls.Add(this.btn_New);
            this.Controls.Add(this.btn_Register);
            this.Controls.Add(this.btn_Update);
            this.Controls.Add(this.btn_Delete);
            this.Controls.Add(this.btn_Clear);
            this.Controls.Add(this.btn_Cancel);
            this.Controls.Add(this.dgv_TransportList);
            this.BackgroundImage = global::ESHIFT.Properties.Resources.ChatGPT_Image_Sep_8__2025__12_43_24_AM;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "TransportUnit";
            this.Text = "TransportUnit";
            this.Load += new System.EventHandler(this.TransportUnit_Load);
            this.grp_Search.ResumeLayout(false);
            this.grp_Search.PerformLayout();
            this.grp_Vehicle.ResumeLayout(false);
            this.grp_Vehicle.PerformLayout();
            this.grp_Driver.ResumeLayout(false);
            this.grp_Driver.PerformLayout();
            this.grp_Assistant.ResumeLayout(false);
            this.grp_Assistant.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_TransportList)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lbl_Title;
        private System.Windows.Forms.GroupBox grp_Search;
        private System.Windows.Forms.Label lbl_SearchBy;
        private System.Windows.Forms.ComboBox cmb_SearchBy;
        private System.Windows.Forms.TextBox txt_Search;
        private System.Windows.Forms.Button btn_Search;
        private System.Windows.Forms.Button btn_ViewAll;
        private System.Windows.Forms.GroupBox grp_Vehicle;
        private System.Windows.Forms.Label lbl_UnitID;
        private System.Windows.Forms.TextBox txt_UnitID;
        private System.Windows.Forms.Label lbl_NumberPlate;
        private System.Windows.Forms.TextBox txt_NumberPlate;
        private System.Windows.Forms.Label lbl_ContainerID;
        private System.Windows.Forms.TextBox txt_ContainerID;
        private System.Windows.Forms.Label lbl_Status;
        private System.Windows.Forms.ComboBox cmb_Status;
        private System.Windows.Forms.GroupBox grp_Driver;
        private System.Windows.Forms.Label lbl_DriverName;
        private System.Windows.Forms.TextBox txt_DriverName;
        private System.Windows.Forms.Label lbl_DriverPhone;
        private System.Windows.Forms.TextBox txt_DriverPhone;
        private System.Windows.Forms.Label lbl_DriverNIC;
        private System.Windows.Forms.TextBox txt_DriverNIC;
        private System.Windows.Forms.GroupBox grp_Assistant;
        private System.Windows.Forms.Label lbl_AssistantName;
        private System.Windows.Forms.TextBox txt_AssistantName;
        private System.Windows.Forms.Label lbl_AssistantPhone;
        private System.Windows.Forms.TextBox txt_AssistantPhone;
        private System.Windows.Forms.Label lbl_AssistantNIC;
        private System.Windows.Forms.TextBox txt_AssistantNIC;
        private System.Windows.Forms.Button btn_Register;
        private System.Windows.Forms.Button btn_New;
        private System.Windows.Forms.Button btn_Update;
        private System.Windows.Forms.Button btn_Delete;
        private System.Windows.Forms.Button btn_Clear;
        private System.Windows.Forms.Button btn_Cancel;
        private System.Windows.Forms.DataGridView dgv_TransportList;
        private System.Windows.Forms.Label lbl_VehicleType;
        private System.Windows.Forms.TextBox txt_VehicleType;
        private System.Windows.Forms.Button btn_ShowJob;
    }
}
